### ISSUE TITLE
Open graphic image for the package

### ISSUE THREAD

**Issue by Sayani07** [ropenscilabs/gghdr#10]
An image to be used when we are posting about the package.

**Comment by mitchelloharawild** [comment]
![image](https://user-images.githubusercontent.com/16127127/70776411-1a030f80-1dd1-11ea-966e-886f64e4449f.png)

**Comment by emitanaka** [comment]
How about this? https://unsplash.com/photos/cqbLg3lZEpk

**Comment by mitchelloharawild** [comment]
Added in https://github.com/Sayani07/gghdr/commit/5c846d0ed6d90b0a2d5e52a810d5e75f6ba52bdc

**Comment by mitchelloharawild** [comment]
![image](https://user-images.githubusercontent.com/16127127/150286125-67a140ea-d590-49c7-8e96-f348132ef36d.png)
