### ISSUE TITLE
Adding mode to geom_hdr_rug

### ISSUE THREAD

**Issue by Sayani07** [ropenscilabs/gghdr#11]

**Comment by sparce** [comment]
Added as lines for consistency with `geom_hdr_boxplot`. I'm not convinced that a line is the right choice for the rug that sits up against the axes however. Maybe we should consider using a point for this instead?

```
ggplot(faithful, aes(y = eruptions, x = waiting)) + 
    geom_hdr_rug(sides = "trbl") + 
    geom_point() + 
    theme_bw()
```
![rug](https://user-images.githubusercontent.com/36123293/70856432-3fa72a80-1f31-11ea-8170-f66c3ba25779.png)

**Comment by mitchelloharawild** [comment]
I like the lines.

**Comment by emitanaka** [comment]
+1 to lines

**Comment by mitchelloharawild** [comment]
LGTM, closing as it has been added :tada:
