### ISSUE TITLE
Write a rOpenSci blog post

### ISSUE THREAD

**Issue by mitchelloharawild** [ropenscilabs/gghdr#13]
@stefaniebutland has invited us to write a blog post about our project.
It will be published on the rOpenSci blog, https://ropensci.org/blog/

You can read posts from previous ozunconf projects to get an idea of what this involves:
* https://ropensci.org/tags/ozunconf16
* https://ropensci.org/tags/ozunconf17
* https://ropensci.org/tags/ozunconf18

The post could include things about:
* What the package does
* Why we made it how we did
* Experiences and challenges in the project (merge conflicts?)
* Distractions along the way ([*just typing R code*](https://twitter.com/mitchoharawild/status/1205008586130149376))

Let me know if you're interested in writing this post - I'm sure each of us have something to share about this project.
@Sayani07 @sparce @Ryo-N7 @dvanic @emitanaka @thomas-fung

**Comment by stefaniebutland** [comment]
Don't be shy folks. Typically for posts about rOpenSci unconf projects, it's ideal if all team members are authors because everyone contributed to the project.

Looking forward to reading it!

**Comment by Sayani07** [comment]
Happy new year everyone! Hope you are doing great. I was on a long leave and joined back recently. This is great. Thanks @stefaniebutland. I was wondering if someone already got started on this. Else I can have a draft ready by this weekend and send it across for each of you to add your experiences.

**Comment by stefaniebutland** [comment]
Glad to hear you're interested @Sayani07. Please coordinate with @mitchelloharawild

**Comment by mitchelloharawild** [comment]
No one has started working on this yet. If you'd like to write the draft or structure, that would be great.
I can set up a branch for this on the repo to organise our efforts.

**Comment by dvanic** [comment]
I'm happy to hel, too! Should have some time this week

**Comment by Sayani07** [comment]
Hello people! I have added a rough draft  at https://github.com/ropenscilabs/gghdr/blob/blog_branch/vignettes/blog.Rmd. This is the first time I gave a shot to blogging. So please consider suggesting changes in context and tone, if required. Also could you please add each of your experiences.

**Comment by stefaniebutland** [comment]
Thank you @Sayani07. I won't review anything till you and your team say you're ready. At that point, I'll send instructions for you to make a pull request (we're currently updating them).

@dvanic @mitchelloharawild & others, please comment ☝️

**Comment by emitanaka** [comment]
The draft looks great @Sayani07 ! Couple of photos to be included are missing but the boxplots are not showing up for me so maybe some final checks before the blog can go up

**Comment by Sayani07** [comment]
Thanks @emitanaka for having a look. I have added the picture and included the codes from cde branch to show conditional density estimation.  But I will write some tests before it goes up.

Can someone edit the section on challenges faced?

**Comment by mitchelloharawild** [comment]
@njtierney Is rOpenSci still interested in this blog post? Sayani says it's ready to go and we're preparing for a CRAN release today.

**Comment by njtierney** [comment]
I believe so! I would just double check with @steffilazerte - could Mitch and Sayani contribute their blog post to rOpenSci?

**Comment by steffilazerte** [comment]
:tada: Absolutely! Check out the [Blog Guide](https://blogguide.ropensci.org/) for instructions for blog posts and submitting. When you're ready to go just ping me in the Pull Request comments and I'll give it a review.
Thanks!

**Comment by Sayani07** [comment]
Blog post likely to be published by 15th February!
