### ISSUE TITLE
fill color doesn't match up with legend key

### ISSUE THREAD

**Issue by emitanaka** [ropenscilabs/gghdr#15]
In below example the legend key doesn't have the same fill color.

```
library(gghdr)
library(ggplot2)
ggplot(faithful, aes(y = eruptions)) + 
  geom_hdr_boxplot(prob = c(.5, 0.99), fill = "blue") + 
  theme_minimal()
```

![download](https://user-images.githubusercontent.com/7620319/74885409-9154b100-53c9-11ea-88e5-6a90fb7ab0a7.png)

**Comment by mitchelloharawild** [comment]
I think of the legend for level here as more of a shade rather than fill
colour. If anything, the default fill colour for the box should be
grayscale.

The grayscale colour scheme is for the legend to make sense when the fill
varies in the plot.

**Comment by emitanaka** [comment]
I guess here's what you mean about the shading: 
![download (1)](https://user-images.githubusercontent.com/7620319/74886705-f8c03000-53cc-11ea-82b4-a29eb23f0c73.png)
Slightly awkward for single color case above but understandable for above case.

**Comment by mitchelloharawild** [comment]
I don't feel strongly about the single colour case, but my two reasons not to do it are:
* Inconsistency
* I think it's hard :see_no_evil:

If you wanted to try, feel free. I think Rob has some stronger opinions about the single colour case.

**Comment by thomas-fung** [comment]
In an earlier attempt, it was possible to match the legend key and (most of) the fill colour. Obviously the code would need to be flexible enough to allow an arbitrary number of shades and the way we did it was to scale a particular attribute of a colouring system to create different level of shades. But it would fall apart if the fill colour has a low or zero value for such attribute such as "black". We can obviously manage these cases but it would create inconsistency just like Mitch said.
