### ISSUE TITLE
Transfer to personal account?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/gghdr#18]
@mitchelloharawild @Sayani07 et al :wave: according to our [recently created package curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages) this repo should now be transferred to either one of your personal accounts, or the ropensci-archive organization.

If you don't answer within one month, I'll transfer the repository to ropensci-archive, after which you could still email me to transfer the repo to a personal account.

Thank you!

**Comment by mitchelloharawild** [comment]
At first preference I think the repo owner should be @Sayani07. If Sayani is not interested in owning and maintaining the package it can be transferred to my account.

**Comment by Sayani07** [comment]
Thanks @mitchelloharawild! 
@maelle Can you send me an invite for this transfer. Thank you.

**Comment by maelle** [comment]
Thanks both!

@Sayani07 I've just tried the transfer but it seems you have a private fork or a private repo called gghdr.

If I remember correctly renaming that repo won't be enough (if you delete it back it up first :-) ). I am sorry for the clunkiness!

I can try again tomorrow.

**Comment by Sayani07** [comment]
Oh Sorry! I have deleted it now. Please let me know if there is still an issue whenever you try it.

**Comment by mitchelloharawild** [comment]
I have initiated a transfer request :smile:

**Comment by Sayani07** [comment]
Thanks again @mitchelloharawild. Transfer done now.

**Comment by maelle** [comment]
Awesome, thanks both!
