### ISSUE TITLE
Hex sticker source files

### ISSUE THREAD

**Issue by mitchelloharawild** [ropenscilabs/gghdr#19]
@emitanaka 
Do you have the source files used to produce the hex sticker? I typically put them in the /hex folder of a repo.
If you have them, could you please provide them?

**Comment by emitanaka** [comment]
Just did a thorough check but unfortunately can't locate it. I suggest we make a new one anyhow because the original one isn't that great

**Comment by mitchelloharawild** [comment]
We'll keep the hex sticker as is, it's good enough. I've brought in the hex sticker from the documentation into /hex.
