### ISSUE TITLE
vdiffr visual regression tests not working

### ISSUE THREAD

**Issue by Ryo-N7** [ropenscilabs/gghdr#7]
possibly due to: https://github.com/r-lib/vdiffr/issues/36

**Comment by Sayani07** [comment]
Any brainstorming on this would be helpful. 
Some of the plot components depend on random variation which might lead to this problem as suggested [here](https://rdrr.io/cran/vdiffr/man/expect_doppelganger.html). The calc.falpha argument used in HDRs do use sampling. Maybe adding an seed here might help. Any suggestions?

**Comment by mitchelloharawild** [comment]
Closing as tests now seem fine. Presumably adding the seed fixed this issue.
